### ISSUE TITLE
Jake Kafrissen Issue

### ISSUE THREAD

**Issue by jakekafrissen** [CS-at-GA/00---Setup#20]
Does the why do people use the "$" instead of the "$$" format of code and vice versa?

**Comment by gajoswald** [comment]
Not sure I am following... more context?

**Comment by jakekafrissen** [comment]
> Not sure I am following... more context?

I was referring to using markdown to write mathematical expressions on Github. The description says, "To add a math expression as a block, start a new line and delimit the expression with two dollar symbols $$", but before that, it says, "This sentence uses `$` delimiters to show math inline:  $\sqrt{3x-1}+(1+x)^2$". Where would we use one versus the other in coding for mathematical equations?

**Comment by jakekafrissen** [comment]
I hope that clears up my question.

**Comment by gajoswald** [comment]
Ahh, I see. You use the $​ to surround mathematical expressions. On its own, in markdown, it doesn't mean anything.


Jason Oswald

he/him/his

pronouns matter<https://www.mypronouns.org/>

schedule a time to ***@***.***/bookings/>

zoom<https://germantownacademy.zoom.us/j/3770382758>

________________________________
From: jakekafrissen ***@***.***>
Sent: Monday, October 10, 2022 8:08 PM
To: CS-at-GA/00---Setup ***@***.***>
Cc: Jason Oswald ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL]Re: [CS-at-GA/00---Setup] Jake Kafrissen Issue (Issue #20)


[EXTERNAL]

Not sure I am following... more context?

I was referring to using markdown to write mathematical expressions on Github. The description says, "To add a math expression as a block, start a new line and delimit the expression with two dollar symbols $$", but before that, it says, "This sentence uses $ delimiters to show math inline: $\sqrt{3x-1}+(1+x)^2$". Where would we use one versus the other in coding for mathematical equations?
