### ISSUE TITLE
Ryan Barrett

### ISSUE THREAD

**Issue by ryanbarrett24** [CS-at-GA/00---Setup#23]
Here's my fantasy football team. Rate it please!
QB - Jalen Hurts
RB - Christian McCaffrey
RB - Leonard Fournette
WR - Courtland Sutton
WR - Tyreek Hill
TE - Darren Waller
D/ST - Bills
K - Evan McPherson

**Comment by gajoswald** [comment]
hahaha... I'm afraid I have zero skills in this area, but we do like the Cheetah!
