### ISSUE TITLE
my code is not doing what i want (test)Help Request

### ISSUE THREAD

**Issue by zachmateo** [CS-at-GA/00---Setup#9]
1. I am trying to ____
2. I did ____ and was expecting ____, but instead
3. Could this because ____, ____, or ____?
4. This seems impossible because ____, ____, and ____. 
5. I've tried ____, ____, and ____ to fix it but ____. 

My project code is here: 

Remember that you can attach files to this issue request.

**Comment by gajoswald** [comment]
Great!
